version: '3.8'

services:
  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: unibooks
      POSTGRES_PASSWORD: unibooks
      POSTGRES_DB: unibooks
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
